swagger: '2.0'
info:
  title: Calculator API
  version: 1.0.0
  description: A simple calculator API to perform basic arithmetic operations
host: localhost:3000
basePath: /
schemes:
  - http
securityDefinitions:
  apiKeyAuth:
    type: apiKey
    in: header
    name: X-API-Key
paths:
  /:
    get:
      summary: Welcome message
      responses:
        200:
          description: Returns a welcome message.

  /users/validateToken:
    get:
      summary: Validates the API key
      security:
        - apiKeyAuth: []
      responses:
        200:
          description: API key is valid
        401:
          description: Unauthorized, invalid API key

  /api/v1/calculator/add:
    post:
      summary: Adds two numbers
      security:
        - apiKeyAuth: []
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              a:
                type: number
                description: First number
              b:
                type: number
                description: Second number
      responses:
        200:
          description: Result of addition
          schema:
            type: object
            properties:
              result:
                type: number
                description: Sum of the two numbers
        401:
          description: Unauthorized, invalid API key

  /api/v1/calculator/subtract:
    post:
      summary: Subtracts two numbers
      security:
        - apiKeyAuth: []
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              a:
                type: number
                description: First number
              b:
                type: number
                description: Second number
      responses:
        200:
          description: Result of subtraction
          schema:
            type: object
            properties:
              result:
                type: number
                description: Result of subtraction
        401:
          description: Unauthorized, invalid API key

  /api/v1/calculator/multiply:
    post:
      summary: Multiplies two numbers
      security:
        - apiKeyAuth: []
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              a:
                type: number
                description: First number
              b:
                type: number
                description: Second number
      responses:
        200:
          description: Result of multiplication
          schema:
            type: object
            properties:
              result:
                type: number
                description: Result of multiplication
        401:
          description: Unauthorized, invalid API key

  /api/v1/calculator/divide:
    post:
      summary: Divides two numbers
      security:
        - apiKeyAuth: []
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              a:
                type: number
                description: First number
              b:
                type: number
                description: Second number
      responses:
        200:
          description: Result of division
          schema:
            type: object
            properties:
              result:
                type: number
                description: Result of division
        401:
          description: Unauthorized, invalid API key
